version: '3.9'
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    container_name: backend
    build: ./
    restart: 'unless-stopped'
    ports:
      - '3005:3005'
    env_file:
      - ./.env
    depends_on:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017
